import { motion } from 'framer-motion';
import Link from 'next/link';
import Layout from '@/components/layout/Layout';
import { productPageFont } from '@/lib/productPageTypography';
import {
  Search, BarChart2, TrendingUp, Shield, Database,
  ArrowRight, CheckCircle, Zap, Target, Users,
  PieChart, LineChart, FileText, AlertCircle, Activity,
} from 'lucide-react';

/* ─── Color tokens ─────────────────────────────────────────── */
const EMERALD = '#10b981';
const VIOLET  = '#7c3aed';
const TEAL    = '#0d9488';

/* ─── SSR-safe static data ──────────────────────────────────── */
const PARTICLES = [
  { x: 10, y: 15, r: 1.5, dur: 3.4, d: 0.0, c: EMERALD },
  { x: 82, y: 10, r: 1.0, dur: 4.2, d: 0.5, c: TEAL    },
  { x: 90, y: 55, r: 2.0, dur: 3.9, d: 1.0, c: VIOLET  },
  { x: 18, y: 80, r: 1.5, dur: 4.6, d: 0.2, c: EMERALD },
  { x: 65, y: 90, r: 1.0, dur: 3.6, d: 0.8, c: TEAL    },
  { x: 45, y:  6, r: 2.0, dur: 4.3, d: 1.2, c: EMERALD },
  { x: 94, y: 35, r: 1.0, dur: 4.0, d: 0.6, c: VIOLET  },
  { x:  6, y: 50, r: 1.5, dur: 4.8, d: 1.5, c: TEAL    },
  { x: 55, y: 96, r: 1.5, dur: 3.4, d: 0.9, c: EMERALD },
  { x: 74, y:  3, r: 1.0, dur: 5.2, d: 0.1, c: VIOLET  },
];

const QUERY_NODES = [
  { label: 'Commercial Data', cx: 80,  cy: 120, c: TEAL    },
  { label: 'Sales Data',      cx: 420, cy: 120, c: EMERALD },
  { label: 'Query Parser',   cx: 420, cy: 400, c: VIOLET  },
  { label: 'Insight Engine', cx: 80,  cy: 400, c: TEAL    },
  { label: 'Audit Trail',    cx: 250, cy: 470, c: EMERALD },
  { label: 'NLU Core',       cx: 250, cy: 50,  c: VIOLET  },
];

const PIPELINE_STEPS = [
  { label: 'Natural Language Input',  sub: 'Question parsing',     icon: Search,   color: TEAL    },
  { label: 'Data Retrieval',          sub: 'Licensed dataset retrieval', icon: Database, color: EMERALD },
  { label: 'Deterministic Analysis',  sub: 'Zero-hallucination',   icon: Zap,      color: VIOLET  },
  { label: 'Cited Output',            sub: 'Source-linked answer', icon: FileText, color: TEAL    },
  { label: 'Audit Record',            sub: 'Full query trail',      icon: Shield,   color: EMERALD },
];

const FEATURES = [
  {
    icon: Search,
    title: 'Natural Language Q&A',
    desc: 'Ask any market question in plain English — market share, growth, rankings, competitive position — answered instantly from your own data.',
    accent: TEAL,
  },
  {
    icon: Target,
    title: 'Strategic Recommendations',
    desc: 'Investment priority scores, therapy attractiveness analysis, and portfolio diagnostics delivered as CXO-ready narratives, not raw charts.',
    accent: EMERALD,
  },
  {
    icon: BarChart2,
    title: 'Competitive Intelligence',
    desc: 'Track segment leadership, share movement, competitive concentration, and white-space opportunities across therapies, molecules, and geographies.',
    accent: VIOLET,
  },
  {
    icon: TrendingUp,
    title: 'Growth Diagnostics',
    desc: 'Identifies what is driving or dragging a brand — decomposed by volume, price, geography, new SKUs, and therapy mix.',
    accent: TEAL,
  },
  {
    icon: LineChart,
    title: 'Sales Forecasting',
    desc: '12-month brand and therapy-level forecasts with confidence ranges, built entirely from your licensed pharma commercial datasets.',
    accent: EMERALD,
  },
  {
    icon: Shield,
    title: 'Audit-Grade Outputs',
    desc: 'Every answer is cited to the source metric. Numbers come from data, not generated by AI. Full query audit trail included.',
    accent: VIOLET,
  },
];

const USE_CASES = [
  {
    icon: Users,
    title: 'CXO / Business Head',
    desc: 'Investment prioritisation and portfolio strategy from live market data — no analyst prep, no waiting for the weekly report.',
    accent: EMERALD,
    large: true,
  },
  {
    icon: Target,
    title: 'Brand Manager',
    desc: 'Real-time share tracking, competitor moves, and growth diagnostics for every brand in your portfolio.',
    accent: TEAL,
    large: false,
  },
  {
    icon: TrendingUp,
    title: 'Sales & Marketing',
    desc: 'Therapy and geography priorities backed by deterministic market metrics — not gut feel, not last quarter\'s data.',
    accent: VIOLET,
    large: false,
  },
  {
    icon: PieChart,
    title: 'Market Research',
    desc: 'Instant deep-dives across licensed commercial pharma datasets — no Excel, no analyst wait time, no version confusion.',
    accent: EMERALD,
    large: false,
  },
];

const OLD_WAY = [
  'Wait 3–5 days for analyst to pull and format commercial pharma reports',
  'Static Excel outputs that are stale within days',
  'Insights depend on individual analyst skill and availability',
  'No audit trail — unclear where numbers came from',
  'Scaling insights requires scaling analyst headcount',
];

const NEW_WAY = [
  'Any market question answered in under 15 seconds',
  'Always-current data from your licensed pharma commercial datasets',
  'Deterministic retrieval — same question gives the same answer every time',
  'Every number cited to its exact source metric',
  'Any number of questions, any time, with no additional cost',
];

const INTEGRITY_PILLARS = [
  {
    icon: Database,
    title: 'Deterministic Retrieval',
    desc: 'Answers are retrieved from your data — not generated by the model. No confabulation, no approximation.',
  },
  {
    icon: Shield,
    title: 'Zero Hallucination',
    desc: 'If the answer does not exist in the licensed dataset, PharmaAI says so explicitly rather than generating a plausible-sounding number.',
  },
  {
    icon: FileText,
    title: 'Source Citation',
    desc: 'Every metric in every answer is linked to its originating record. Reviewable, auditable, defensible.',
  },
  {
    icon: Activity,
    title: 'Query Audit Trail',
    desc: 'Full log of every question asked, every data record retrieved, every answer delivered — for compliance and governance.',
  },
];

const fadeUp = {
  hidden: { opacity: 0, y: 28 },
  show:   { opacity: 1, y: 0, transition: { duration: 0.65 } },
};

/* ═══════════════════════════════════════════════════════════════
   HERO VISUALIZATION — Intelligence Query Core
═══════════════════════════════════════════════════════════════ */
function IntelligencePipeline() {
  const W = 500, H = 520, CX = 250, CY = 260;

  return (
    <div className="relative w-full max-w-[500px] h-[520px] select-none">

      {/* Ambient sphere glow */}
      <div className="pointer-events-none absolute" style={{
        top: '50%', left: '50%',
        transform: 'translate(-50%,-50%)',
        width: '340px', height: '340px', borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(16,185,129,0.20) 0%, transparent 70%)',
        filter: 'blur(48px)',
      }} />

      {/* SVG: orbit rings + neural lines */}
      <svg className="absolute inset-0 w-full h-full" viewBox={`0 0 ${W} ${H}`} fill="none">
        {/* Orbit ring 1 */}
        <ellipse cx={CX} cy={CY} rx="210" ry="55"
          stroke="rgba(16,185,129,0.15)" strokeWidth="1" strokeDasharray="3 7" />
        {/* Orbit ring 2 */}
        <ellipse cx={CX} cy={CY} rx="55" ry="210"
          stroke="rgba(13,148,136,0.12)" strokeWidth="1" />
        {/* Orbit ring 3 — diagonal */}
        <ellipse cx={CX} cy={CY} rx="178" ry="64"
          transform={`rotate(38, ${CX}, ${CY})`}
          stroke="rgba(124,58,237,0.12)" strokeWidth="1" strokeDasharray="6 4" />

        {/* Neural connection lines */}
        {QUERY_NODES.map((n, i) => (
          <motion.line key={i}
            x1={CX} y1={CY} x2={n.cx} y2={n.cy}
            stroke={i % 2 === 0 ? 'rgba(16,185,129,0.18)' : 'rgba(13,148,136,0.14)'}
            strokeWidth="1" strokeDasharray="4 6"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1.2, delay: i * 0.15 + 0.6 }}
          />
        ))}

        {/* Traveling dot — equatorial ring */}
        <motion.circle r="3" fill={EMERALD}
          filter="url(#glow-em)"
          animate={{ rotate: 360 }}
          style={{ transformOrigin: `${CX}px ${CY}px` }}
          transition={{ duration: 6, repeat: Infinity, ease: 'linear' }}
        >
          <animateMotion dur="6s" repeatCount="indefinite"
            path={`M ${CX + 210} ${CY} A 210 55 0 1 1 ${CX + 209.9} ${CY}`} />
        </motion.circle>

        {/* Traveling dot — vertical ring */}
        <motion.circle r="2.5" fill={TEAL}
          filter="url(#glow-tl)"
        >
          <animateMotion dur="8s" repeatCount="indefinite"
            path={`M ${CX} ${CY - 210} A 55 210 0 1 1 ${CX} ${CY + 210} A 55 210 0 1 1 ${CX} ${CY - 210}`} />
        </motion.circle>

        {/* Peripheral node dots */}
        {QUERY_NODES.map((n, i) => (
          <motion.g key={i}
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5, delay: i * 0.12 + 0.8 }}
            style={{ transformOrigin: `${n.cx}px ${n.cy}px` }}
          >
            <circle cx={n.cx} cy={n.cy} r="18" fill={`${n.c}10`} />
            <circle cx={n.cx} cy={n.cy} r="10" fill={`${n.c}20`} />
            <circle cx={n.cx} cy={n.cy} r="4"  fill={n.c} />
            <motion.circle cx={n.cx} cy={n.cy} r="10"
              stroke={n.c} strokeWidth="0.8" fill="none"
              animate={{ r: [10, 18, 10], opacity: [0.5, 0, 0.5] }}
              transition={{ duration: 2.5, repeat: Infinity, delay: i * 0.4 }}
            />
          </motion.g>
        ))}

        {/* Node labels */}
        {QUERY_NODES.map((n, i) => {
          const labelX = n.cx > CX ? n.cx + 24 : n.cx - 24;
          const anchor = n.cx > CX ? 'start' : 'end';
          return (
            <motion.text key={i} x={labelX} y={n.cy + 4}
              textAnchor={anchor} fontSize="9" fill="rgba(255,255,255,0.45)"
              initial={{ opacity: 0 }} animate={{ opacity: 1 }}
              transition={{ delay: i * 0.12 + 1.2 }}
            >
              {n.label}
            </motion.text>
          );
        })}

        <defs>
          <filter id="glow-em" x="-100%" y="-100%" width="300%" height="300%">
            <feGaussianBlur stdDeviation="3" result="b" />
            <feMerge><feMergeNode in="b" /><feMergeNode in="SourceGraphic" /></feMerge>
          </filter>
          <filter id="glow-tl" x="-100%" y="-100%" width="300%" height="300%">
            <feGaussianBlur stdDeviation="2.5" result="b" />
            <feMerge><feMergeNode in="b" /><feMergeNode in="SourceGraphic" /></feMerge>
          </filter>
        </defs>
      </svg>

      {/* Center: Core Intelligence sphere */}
      <div className="pointer-events-none absolute" style={{
        top: '50%', left: '50%',
        transform: 'translate(-50%,-50%)',
        width: '110px', height: '110px',
      }}>
        <motion.div className="absolute inset-0 rounded-full"
          style={{ background: `radial-gradient(circle, ${EMERALD}30 0%, ${TEAL}15 60%, transparent 100%)` }}
          animate={{ scale: [1, 1.12, 1] }}
          transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}
        />
        <div className="absolute inset-[14px] rounded-full"
          style={{
            background: 'rgba(5,8,22,0.92)',
            border: `1px solid ${EMERALD}35`,
            boxShadow: `0 0 30px ${EMERALD}25, inset 0 1px 0 rgba(255,255,255,0.06)`,
          }}
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-0.5">
          <span className="text-[10px] font-bold uppercase tracking-widest" style={{ color: EMERALD }}>PharmaAI</span>
          <span className="text-[8px] text-white/40">Intelligence Core</span>
        </div>
      </div>

      {/* Float panel: Query input */}
      <motion.div className="absolute right-2 top-16 w-44 overflow-hidden rounded-2xl"
        style={{
          background: 'rgba(5,8,22,0.88)',
          border: `1px solid ${TEAL}30`,
          backdropFilter: 'blur(20px)',
          boxShadow: `0 8px 32px rgba(0,0,0,0.55), inset 0 1px 0 rgba(255,255,255,0.04)`,
        }}
        initial={{ opacity: 0, x: 22 }} animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 1.4, duration: 0.6 }}
      >
        <div className="border-b border-white/5 px-3 py-2">
          <span className="text-[9px] font-semibold uppercase tracking-widest" style={{ color: `${TEAL}99` }}>Query</span>
        </div>
        <div className="px-3 py-2.5">
          <div className="mb-1 text-[10px] text-white/60">Market share of brand X in therapy Y?</div>
          <div className="flex items-center gap-1.5 mt-1.5">
            <motion.div className="h-1.5 w-1.5 rounded-full"
              style={{ background: EMERALD }}
              animate={{ opacity: [1, 0.25, 1] }}
              transition={{ duration: 1.1, repeat: Infinity }} />
            <span className="text-[9px]" style={{ color: `${EMERALD}99` }}>Retrieving…</span>
          </div>
        </div>
      </motion.div>

      {/* Float panel: Answer */}
      <motion.div className="absolute left-2 bottom-28 w-44 overflow-hidden rounded-2xl"
        style={{
          background: 'rgba(5,8,22,0.88)',
          border: `1px solid ${EMERALD}30`,
          backdropFilter: 'blur(20px)',
          boxShadow: `0 8px 32px rgba(0,0,0,0.55), inset 0 1px 0 rgba(255,255,255,0.04)`,
        }}
        initial={{ opacity: 0, x: -22 }} animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 2.0, duration: 0.6 }}
      >
        <div className="border-b border-white/5 px-3 py-2">
          <span className="text-[9px] font-semibold uppercase tracking-widest" style={{ color: `${EMERALD}99` }}>Answer · Cited</span>
        </div>
        <div className="px-3 py-2.5">
          <div className="text-[11px] font-semibold text-white/80">18.4% MAT share</div>
          <div className="text-[9px] mt-0.5" style={{ color: `${TEAL}99` }}>Source: Licensed Dataset · Q1-2026</div>
          <div className="mt-2 flex items-center gap-1.5">
            <div className="h-1 flex-1 overflow-hidden rounded-full" style={{ background: `${EMERALD}15` }}>
              <motion.div className="h-full rounded-full"
                style={{ background: `linear-gradient(90deg, ${EMERALD}, ${TEAL})` }}
                animate={{ width: ['0%', '100%'] }}
                transition={{ duration: 0.8, delay: 2.4 }}
              />
            </div>
            <span className="text-[9px]" style={{ color: `${EMERALD}80` }}>100%</span>
          </div>
        </div>
      </motion.div>

      {/* Float panel: Processing */}
      <motion.div className="absolute top-36 left-2 w-40 overflow-hidden rounded-2xl"
        style={{
          background: 'rgba(5,8,22,0.88)',
          border: `1px solid ${VIOLET}30`,
          backdropFilter: 'blur(20px)',
          boxShadow: `0 8px 32px rgba(0,0,0,0.55), inset 0 1px 0 rgba(255,255,255,0.04)`,
        }}
        initial={{ opacity: 0, x: -22 }} animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 1.9, duration: 0.6 }}
      >
        <div className="px-3 py-2.5">
          <div className="mb-1 flex items-center gap-2">
            <motion.div className="h-1.5 w-1.5 rounded-full" style={{ background: VIOLET }}
              animate={{ opacity: [1, 0.25, 1] }} transition={{ duration: 1.1, repeat: Infinity }} />
            <span className="text-[9px] font-semibold uppercase tracking-widest" style={{ color: `${VIOLET}99` }}>Processing</span>
          </div>
          <div className="text-[10px] text-white/55">Deterministic Retrieval</div>
          <div className="text-[9px]" style={{ color: `${VIOLET}70` }}>Zero hallucination…</div>
        </div>
      </motion.div>

      {/* Particle field */}
      {PARTICLES.map((p, i) => (
        <motion.div key={i} className="pointer-events-none absolute rounded-full" style={{
          left: `${p.x}%`, top: `${p.y}%`,
          width: `${p.r * 2}px`, height: `${p.r * 2}px`,
          background: p.c, boxShadow: `0 0 ${p.r * 4}px ${p.c}`,
        }}
          animate={{ y: [0, -10, 0], opacity: [0.22, 0.72, 0.22] }}
          transition={{ duration: p.dur, repeat: Infinity, delay: p.d, ease: 'easeInOut' }}
        />
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   PIPELINE VISUALIZATION
═══════════════════════════════════════════════════════════════ */
function QueryPipelineViz() {
  return (
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
      {PIPELINE_STEPS.map((step, i) => {
        const Icon = step.icon;
        return (
          <div key={i} className="flex items-center gap-3 lg:flex-col lg:text-center lg:gap-2 lg:flex-1">
            <motion.div
              className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl"
              style={{
                background: `${step.color}15`,
                border: `1px solid ${step.color}30`,
                boxShadow: `0 0 16px ${step.color}15`,
              }}
              initial={{ opacity: 0, scale: 0.8 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 + 0.3 }}
            >
              <Icon className="h-5 w-5" style={{ color: step.color }} />
            </motion.div>
            <div>
              <div className="text-[11px] font-semibold text-white/80">{step.label}</div>
              <div className="text-[10px] text-white/40">{step.sub}</div>
            </div>
            {i < PIPELINE_STEPS.length - 1 && (
              <motion.div className="hidden lg:block lg:shrink-0"
                animate={{ opacity: [0.3, 0.8, 0.3] }}
                transition={{ duration: 2, repeat: Infinity, delay: i * 0.3 }}
              >
                <ArrowRight className="h-4 w-4 text-white/20" />
              </motion.div>
            )}
          </div>
        );
      })}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   PAGE
═══════════════════════════════════════════════════════════════ */
export default function PharmaAIPage() {
  return (
    <Layout
      title="PharmaAI — Pharma Market Intelligence Platform | DSeT Consulting"
      description="PharmaAI by DSeT Consulting delivers instant, cited pharma market intelligence from licensed commercial datasets in under 15 seconds. Zero hallucination, fully auditable. Designed for pharma commercial teams."
      jsonLd={{
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'PharmaAI',
        applicationCategory: 'BusinessApplication',
        operatingSystem: 'Cloud, SaaS',
        description: 'AI-powered pharma market intelligence platform — instant, cited answers from licensed commercial datasets with zero hallucination and full audit trail.',
        keywords: 'pharma market intelligence AI India, pharma commercial intelligence platform, pharma AI analytics, brand tracking pharma AI, drug market analysis India',
        provider: { '@type': 'Organization', name: 'DSeT Consulting', url: 'https://dsetconsulting.com' },
        url: 'https://dsetconsulting.com/product/pharmaai',
      }}
      breadcrumbs={[
        { name: 'Home', href: '/' },
        { name: 'Platforms', href: '/product' },
        { name: 'PharmaAI', href: '/product/pharmaai' },
      ]}
    >
      <main className={`min-h-screen bg-[#030712] text-white ${productPageFont.variable}`}
        style={{ fontFamily: 'var(--font-product-page)' }}>

        {/* ── HERO ─────────────────────────────────────────────── */}
        <section className="relative overflow-hidden pt-24 pb-20 lg:pt-32 lg:pb-28">
          {/* Background grid */}
          <div className="pointer-events-none absolute inset-0"
            style={{
              backgroundImage: `
                linear-gradient(rgba(16,185,129,0.04) 1px, transparent 1px),
                linear-gradient(90deg, rgba(16,185,129,0.04) 1px, transparent 1px)
              `,
              backgroundSize: '60px 60px',
            }}
          />
          {/* Radial glow */}
          <div className="pointer-events-none absolute inset-0"
            style={{ background: 'radial-gradient(ellipse 80% 50% at 50% 0%, rgba(16,185,129,0.12) 0%, transparent 70%)' }}
          />

          <div className="relative mx-auto max-w-7xl px-6 lg:px-8">
            <div className="grid items-center gap-16 lg:grid-cols-2">

              {/* Left — copy */}
              <div>
                <motion.div className="mb-5 inline-flex items-center gap-2 rounded-full border px-3 py-1.5"
                  style={{ borderColor: `${EMERALD}30`, background: `${EMERALD}0a` }}
                  initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                >
                  <motion.span className="h-1.5 w-1.5 rounded-full"
                    style={{ background: EMERALD, display: 'inline-block' }}
                    animate={{ scale: [1, 1.5, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  />
                  <span className="text-xs font-medium" style={{ color: EMERALD }}>Pharma · Commercial Intelligence</span>
                </motion.div>

                <motion.h1
                  className="mb-6 text-4xl font-bold leading-[1.08] tracking-tight lg:text-5xl xl:text-6xl"
                  initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.15 }}
                >
                  Market intelligence<br />
                  <span style={{
                    background: `linear-gradient(135deg, ${EMERALD} 0%, ${TEAL} 50%, ${VIOLET} 100%)`,
                    WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
                  }}>
                    answered in 15 seconds
                  </span>
                </motion.h1>

                <motion.p
                  className="mb-10 text-base leading-relaxed text-white/55 lg:text-lg"
                  initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.28 }}
                >
                  PharmaAI delivers instant, trustworthy answers from your licensed pharma commercial datasets — without dashboards,
                  Excel reports, or analyst wait time. Ask any market question in plain English. Get a cited,
                  evidence-backed insight in under 15 seconds.
                </motion.p>

                <motion.div className="flex flex-wrap gap-4"
                  initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.4 }}
                >
                  <Link href="/contact?type=demo&product=pharmaai"
                    className="inline-flex items-center gap-2 rounded-xl px-6 py-3 text-sm font-semibold text-white transition-all hover:brightness-110"
                    style={{ background: `linear-gradient(135deg, ${EMERALD}, ${TEAL})`, boxShadow: `0 0 24px ${EMERALD}40` }}
                  >
                    Request Demo <ArrowRight className="h-4 w-4" />
                  </Link>
                  <Link href="/contact?type=talk&product=pharmaai"
                    className="inline-flex items-center gap-2 rounded-xl border px-6 py-3 text-sm font-semibold text-white/70 transition-all hover:text-white hover:border-white/30"
                    style={{ borderColor: 'rgba(255,255,255,0.12)' }}
                  >
                    Talk to us
                  </Link>
                </motion.div>

                {/* Metrics row */}
                <motion.div className="mt-12 flex flex-wrap gap-8"
                  initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                  transition={{ delay: 0.7 }}
                >
                  {[
                    { value: '<15 sec', label: 'Answer time' },
                    { value: 'Zero',    label: 'Hallucination' },
                    { value: 'Full',    label: 'Audit trail' },
                    { value: '100%',    label: 'Cited outputs' },
                  ].map((m, i) => (
                    <div key={i}>
                      <div className="text-2xl font-bold tracking-tight" style={{ color: EMERALD }}>{m.value}</div>
                      <div className="text-xs text-white/40 mt-0.5">{m.label}</div>
                    </div>
                  ))}
                </motion.div>
              </div>

              {/* Right — visualization */}
              <motion.div className="flex justify-center"
                initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.8, delay: 0.3 }}
              >
                <IntelligencePipeline />
              </motion.div>
            </div>
          </div>
        </section>

        {/* ── HOW IT WORKS ─────────────────────────────────────── */}
        <section className="py-20 lg:py-24" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <motion.div className="mb-14 text-center" variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}>
              <div className="mb-3 text-xs font-semibold uppercase tracking-widest" style={{ color: EMERALD }}>How It Works</div>
              <h2 className="text-3xl font-bold lg:text-4xl">From question to cited insight</h2>
              <p className="mt-3 text-white/45">Five-step deterministic pipeline. No guesswork at any stage.</p>
            </motion.div>
            <motion.div variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}>
              <QueryPipelineViz />
            </motion.div>
          </div>
        </section>

        {/* ── FEATURES ─────────────────────────────────────────── */}
        <section className="py-20 lg:py-24" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <motion.div className="mb-14 text-center" variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}>
              <div className="mb-3 text-xs font-semibold uppercase tracking-widest" style={{ color: TEAL }}>Capabilities</div>
              <h2 className="text-3xl font-bold lg:text-4xl">Built for pharma commercial teams</h2>
              <p className="mt-3 text-white/45">Every feature designed around how brand managers, CXOs, and market researchers actually work.</p>
            </motion.div>
            <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {FEATURES.map((f, i) => {
                const Icon = f.icon;
                return (
                  <motion.div key={i}
                    className="rounded-2xl border p-6"
                    style={{
                      borderColor: `${f.accent}20`,
                      background: `linear-gradient(135deg, ${f.accent}08 0%, transparent 100%)`,
                    }}
                    variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}
                    transition={{ delay: i * 0.07 }}
                  >
                    <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl"
                      style={{ background: `${f.accent}15`, border: `1px solid ${f.accent}25` }}>
                      <Icon className="h-5 w-5" style={{ color: f.accent }} />
                    </div>
                    <h3 className="mb-2 text-base font-semibold text-white/90">{f.title}</h3>
                    <p className="text-sm leading-relaxed text-white/50">{f.desc}</p>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ── USE CASES ────────────────────────────────────────── */}
        <section className="py-20 lg:py-24" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <motion.div className="mb-14 text-center" variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}>
              <div className="mb-3 text-xs font-semibold uppercase tracking-widest" style={{ color: VIOLET }}>Use Cases</div>
              <h2 className="text-3xl font-bold lg:text-4xl">Intelligence for every pharma role</h2>
              <p className="mt-3 text-white/45">From CXO strategy to brand-level tracking — one platform, every question answered.</p>
            </motion.div>
            <div className="grid gap-5 lg:grid-cols-4">
              {USE_CASES.map((uc, i) => {
                const Icon = uc.icon;
                return (
                  <motion.div key={i}
                    className={`rounded-2xl border p-6 ${uc.large ? 'lg:col-span-1' : ''}`}
                    style={{
                      borderColor: `${uc.accent}22`,
                      background: `linear-gradient(135deg, ${uc.accent}08 0%, transparent 100%)`,
                    }}
                    variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}
                    transition={{ delay: i * 0.08 }}
                  >
                    <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-xl"
                      style={{ background: `${uc.accent}15`, border: `1px solid ${uc.accent}25` }}>
                      <Icon className="h-5 w-5" style={{ color: uc.accent }} />
                    </div>
                    <h3 className="mb-2 text-sm font-bold text-white/90">{uc.title}</h3>
                    <p className="text-sm leading-relaxed text-white/50">{uc.desc}</p>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ── DATA INTEGRITY ───────────────────────────────────── */}
        <section className="py-20 lg:py-24" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <motion.div className="mb-14 text-center" variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}>
              <div className="mb-3 text-xs font-semibold uppercase tracking-widest" style={{ color: EMERALD }}>Data Integrity</div>
              <h2 className="text-3xl font-bold lg:text-4xl">Zero hallucination is not a claim — it&apos;s an architecture</h2>
              <p className="mt-3 text-white/45">
                PharmaAI retrieves answers from data, not language model inference. Every output is deterministic and auditable.
              </p>
            </motion.div>
            <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
              {INTEGRITY_PILLARS.map((p, i) => {
                const Icon = p.icon;
                return (
                  <motion.div key={i}
                    className="rounded-2xl border p-6"
                    style={{
                      borderColor: `${EMERALD}20`,
                      background: `linear-gradient(135deg, ${EMERALD}06 0%, transparent 100%)`,
                    }}
                    variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                  >
                    <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-xl"
                      style={{ background: `${EMERALD}15`, border: `1px solid ${EMERALD}25` }}>
                      <Icon className="h-4 w-4" style={{ color: EMERALD }} />
                    </div>
                    <h3 className="mb-2 text-sm font-bold text-white/90">{p.title}</h3>
                    <p className="text-xs leading-relaxed text-white/50">{p.desc}</p>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ── OLD WAY vs NEW WAY ───────────────────────────────── */}
        <section className="py-20 lg:py-24" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <motion.div className="mb-14 text-center" variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}>
              <div className="mb-3 text-xs font-semibold uppercase tracking-widest" style={{ color: TEAL }}>Why PharmaAI</div>
              <h2 className="text-3xl font-bold lg:text-4xl">Stop waiting for reports</h2>
            </motion.div>
            <div className="grid gap-6 lg:grid-cols-2">
              {/* Old way */}
              <motion.div className="rounded-2xl border p-8"
                style={{ borderColor: 'rgba(255,255,255,0.07)', background: 'rgba(255,255,255,0.02)' }}
                variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}
              >
                <div className="mb-6 flex items-center gap-3">
                  <div className="flex h-7 w-7 items-center justify-center rounded-full bg-red-500/15">
                    <AlertCircle className="h-3.5 w-3.5 text-red-400" />
                  </div>
                  <span className="text-sm font-bold text-white/60 uppercase tracking-widest">Without PharmaAI</span>
                </div>
                <div className="space-y-4">
                  {OLD_WAY.map((item, i) => (
                    <motion.div key={i} className="flex items-start gap-3 text-sm text-white/45"
                      initial={{ opacity: 0, x: -12 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.07 + 0.4 }}
                    >
                      <div className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-red-400/50" />
                      {item}
                    </motion.div>
                  ))}
                </div>
              </motion.div>

              {/* New way */}
              <motion.div className="rounded-2xl border p-8"
                style={{ borderColor: `${EMERALD}20`, background: `${EMERALD}06` }}
                variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}
                transition={{ delay: 0.1 }}
              >
                <div className="mb-6 flex items-center gap-3">
                  <div className="flex h-7 w-7 items-center justify-center rounded-full" style={{ background: `${EMERALD}20` }}>
                    <CheckCircle className="h-3.5 w-3.5" style={{ color: EMERALD }} />
                  </div>
                  <span className="text-sm font-bold uppercase tracking-widest" style={{ color: EMERALD }}>With PharmaAI</span>
                </div>
                <div className="space-y-4">
                  {NEW_WAY.map((item, i) => (
                    <motion.div key={i} className="flex items-start gap-3 text-sm text-white/70"
                      initial={{ opacity: 0, x: 12 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.07 + 0.5 }}
                    >
                      <motion.span className="mt-1.5 inline-block h-1 w-1 shrink-0 rounded-full"
                        style={{ background: EMERALD }}
                        animate={{ opacity: [0.4, 1, 0.4] }}
                        transition={{ duration: 2, repeat: Infinity, delay: i * 0.3 }}
                      />
                      {item}
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            </div>
          </div>
        </section>

        {/* ── CTA ──────────────────────────────────────────────── */}
        <section className="py-24 lg:py-32" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
          <div className="mx-auto max-w-3xl px-6 text-center">
            <motion.div variants={fadeUp} initial="hidden" whileInView="show" viewport={{ once: true }}>
              <div className="mb-5 text-xs font-semibold uppercase tracking-widest" style={{ color: EMERALD }}>Get Started</div>
              <h2 className="mb-6 text-3xl font-bold lg:text-4xl">
                See PharmaAI answer your first question
              </h2>
              <p className="mb-10 text-base text-white/50">
                Connect your licensed pharma commercial datasets. Ask any market question. Get a cited answer in under 15 seconds.
                No dashboards, no setup, no analyst queue.
              </p>
              <div className="flex flex-wrap justify-center gap-4">
                <Link href="/contact?type=demo&product=pharmaai"
                  className="inline-flex items-center gap-2 rounded-xl px-8 py-4 text-sm font-semibold text-white transition-all hover:brightness-110"
                  style={{ background: `linear-gradient(135deg, ${EMERALD}, ${TEAL})`, boxShadow: `0 0 32px ${EMERALD}40` }}
                >
                  Request a Demo <ArrowRight className="h-4 w-4" />
                </Link>
                <Link href="/contact?type=talk&product=pharmaai"
                  className="inline-flex items-center gap-2 rounded-xl border px-8 py-4 text-sm font-semibold text-white/70 transition-all hover:text-white hover:border-white/30"
                  style={{ borderColor: 'rgba(255,255,255,0.12)' }}
                >
                  Talk to Sales
                </Link>
              </div>
              <p className="mt-6 text-sm text-white/40">
                Ready to go live?{' '}
                <Link href="/dset-arc-managed-intelligence-services" className="text-[#10b981] hover:text-[#10b981]/80 underline underline-offset-2 transition-colors">
                  See how DSeT ARC™ takes PharmaAI from discovery to go-live →
                </Link>
              </p>
            </motion.div>
          </div>
        </section>

      </main>
    </Layout>
  );
}
